stages:
  - build

before_script:
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}

build and push image:
  stage: build
  image: docker:24.0.7-dind
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
  after_script:
    - docker rmi ${CI_REGISTRY_IMAGE}:latest
